version: "3.8"
services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: T123456.a
      MYSQL_DATABASE: sys
    ports:
      - "3307:3306"
    networks:
      - my-network
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8081:8080"
    networks:
      - my-network
    depends_on:
      - mysql-container

networks:
  my-network:
    driver: bridge