version: "3.8"
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - maysql
  maysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: T123456.a
      MYSQL_DATABASE: sys
    ports:
      - "3307:3306"
    networks:
      - network


networks:
  network:
    driver: bridge